import bcrypt from "bcrypt";

const users = [
    {
        name: "John",
        surname: "Doe",
        username: "johndoe",
        email: "johndoe@example.com",
        password: bcrypt.hashSync("password123", 10),
    },
    {
        name: "Jane",
        surname: "Smith",
        username: "janesmith",
        email: "janesmith@example.com",
        password: bcrypt.hashSync("qwerty123", 10),
    },
    {
        name: "Michael",
        surname: "Johnson",
        username: "michaelj",
        email: "michaelj@example.com",
        password: bcrypt.hashSync("abc123", 10),
    },
    {
        name: "Emily",
        surname: "Davis",
        username: "emilyd",
        email: "emilyd@example.com",
        password: bcrypt.hashSync("pass123", 10),
    },
    {
        name: "David",
        surname: "Wilson",
        username: "davidw",
        email: "davidw@example.com",
        password: bcrypt.hashSync("password456", 10),
    },
    {
        name: "Sarah",
        surname: "Taylor",
        username: "saraht",
        email: "saraht@example.com",
        password: bcrypt.hashSync("qwe123", 10),
    },
    {
        name: "Matthew",
        surname: "Anderson",
        username: "matthewa",
        email: "matthewa@example.com",
        password: bcrypt.hashSync("pass456", 10),
    },
    {
        name: "Olivia",
        surname: "Thomas",
        username: "oliviat",
        email: "oliviat@example.com",
        password: bcrypt.hashSync("abc456", 10),
    },
    {
        name: "James",
        surname: "Roberts",
        username: "jamesr",
        email: "jamesr@example.com",
        password: bcrypt.hashSync("pass789", 10),
    },
    {
        name: "Sophia",
        surname: "Clark",
        username: "sophiac",
        email: "sophiac@example.com",
        password: bcrypt.hashSync("qwe456", 10),
    },
    {
        name: "Robert",
        surname: "Lewis",
        username: "robertl",
        email: "robertl@example.com",
        password: bcrypt.hashSync("abc789", 10),
    },
    {
        name: "Ava",
        surname: "Lee",
        username: "avalee",
        email: "avalee@example.com",
        password: bcrypt.hashSync("pass987", 10),
    },
    {
        name: "William",
        surname: "Walker",
        username: "williamw",
        email: "williamw@example.com",
        password: bcrypt.hashSync("qwe789", 10),
    },
    {
        name: "Mia",
        surname: "Hall",
        username: "miah",
        email: "miah@example.com",
        password: bcrypt.hashSync("abc987", 10),
    },
    {
        name: "Benjamin",
        surname: "White",
        username: "benjaminw",
        email: "benjaminw@example.com",
        password: bcrypt.hashSync("pass654", 10),
    },
    {
        name: "Ella",
        surname: "Green",
        username: "ellag",
        email: "ellag@example.com",
        password: bcrypt.hashSync("qwe654", 10),
    },
    {
        name: "Daniel",
        surname: "Baker",
        username: "danielb",
        email: "danielb@example.com",
        password: bcrypt.hashSync("abc654", 10),
    },
    {
        name: "Victoria",
        surname: "Harris",
        username: "victoriah",
        email: "victoriah@example.com",
        password: bcrypt.hashSync("pass321", 10),
    },
    {
        name: "Liam",
        surname: "Martin",
        username: "liamm",
        email: "liamm@example.com",
        password: bcrypt.hashSync("qwe321", 10),
    },
];

export default users;
